#server.port=12000
#spring.application.name=consumer-server
#eureka.client.service-url.defaultZone=http://localhost:13000/eureka,http://localhost:13001/eureka
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=30

server:
  port: 12001
spring:
  application:
    name: service-customer
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.131.33:8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka,http://localhost:13001/eureka

  server:
    enable-self-preservation: false
  instance:
#    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30

#    instance-id: